#!/bin/sh
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/OscamSmartcard 2>/dev/null
echo "**************************************************"
echo "* Successfully removed OscamSmartcard!            *"
echo "**************************************************"