#!/bin/sh
killall -9 /usr/bin/oscam_oscamsmartcard 2>/dev/null
killall -9 /usr/bin/oscam_oscamsmartcard_emu 2>/dev/null
killall -9 /usr/bin/CCcam230 2>/dev/null
killall -9 /usr/bin/CCcam221 2>/dev/null

echo "**************************************************"
echo "create Backup .../etc/tuxbox/config/"
echo "create Backup .../usr/keys/"
tar -cf /etc/tuxbox/config/backup_by_oscamsmartcard.tar.gz /etc/tuxbox/config 2>/dev/null
tar -cf /usr/keys/backup_by_oscamsmartcard.tar.gz /usr/keys  2>/dev/null

#echo "delete old oscam files"
#rm /etc/tuxbox/config/oscam.* 2>/dev/null
#rm /usr/keys/oscam.* 2>/dev/null

#echo "deinstall old oscamsmartcard"
#opkg remove enigma2-plugin-softcams-oscamsmartcard 2>/dev/null
#opkg remove enigma2-plugin-softcams-oscamsmartcard-emu 2>/dev/null
#echo "**************************************************"
