#!/bin/sh
killall -9 /usr/bin/oscam_oscamsmartcard 2>/dev/null
killall -9 /usr/bin/oscam_oscamsmartcard_emu 2>/dev/null
killall -9 /usr/bin/CCcam230 2>/dev/null
killall -9 /usr/bin/CCcam221 2>/dev/null

echo "**************************************************"
echo "create Backup .../etc/tuxbox/config/"
echo "create Backup .../usr/keys/"
tar -cf /etc/tuxbox/config/backup_by_oscamsmartcard.tar.gz /etc/tuxbox/config 2>/dev/null
tar -cf /usr/keys/backup_by_oscamsmartcard.tar.gz /usr/keys  2>/dev/null
